repos:
  # Общие хуки pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace        # убирает пробелы в конце строк
      - id: end-of-file-fixer          # добавляет пустую строку в конце файла
      - id: check-yaml                 # проверяет валидность YAML
      - id: check-added-large-files    # предупреждает про большие файлы
      - id: debug-statements           # предупреждает про debug выражения
      - id: requirements-txt-fixer     # проверяет и фиксирует requirements.txt
      - id: check-merge-conflict       # ловит незакрытые конфликты

  # pycln — удаление неиспользуемых импортов
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln

#  # isort — сортировка импортов
#  - repo: https://github.com/PyCQA/isort
#    rev: v6.0.1  # TODO: версия
#    hooks:
#      - id: isort
#        args: ["--profile", "black"]  # совместимость с Black

  # - add-trailing-comma — добавление запятой в конце
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma

  # Black — автоформатирование кода
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
#        args: ["--config=./pyproject.toml"]

  # Flake8 — проверка стиля и ошибок
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
#        args: ["--config=pyproject.toml"]
        additional_dependencies: [flake8-bugbear]

  # prettier — форматирование Markdown/JSON/YAML/JS/HTML/CSS
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(md|json|yaml|yml|css|js|ts|html|scss)$

  # blacken-docs — форматирование примеров кода в документации
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs