name: Lint

on:
  pull_request:
  push:
    branches: [ dev ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 pycln

      # Black (только проверка)
      - name: Run black
        run: black --check --diff .

      # isort (только проверка)
      - name: Run isort
        run: isort --check-only --diff .

      # pycln (чистка импортов, только проверка)
      - name: Run pycln
        run: pycln --check .

      # flake8 (линтер)
      - name: Run flake8
        run: flake8 .
